create readme
Panchenko-Volodymyr/taxi-service pull request #1
Opened 2021-12-14 20:57 UTC by Panchenko-Volodymyr

2021-12-14 21:15 UTC, zachar-chorny approved these changes

2021-12-15 10:08 UTC, Nick97-git requested changes
- Remove redundant / from endpoints like /cars/, /drivers/ and /manufacturers/ from all places where you use them
- DeleteCarController, DeleteDriverController, DeleteManufacturerController -> remove /all from /cars/all, /drivers/all, /manufacturers/all url patterns

2021-12-15 10:08 UTC, Nick97-git commented on README.md
> +![taxi](https://image.freepik.com/free-vector/taxi-on-the-city_1270-526.jpg)
move image to the next line

2021-12-15 10:08 UTC, Nick97-git commented on README.md
> +* MySQL, MySQL Workbench 8.0
```suggestion
* MySQL
```

2021-12-15 10:08 UTC, Nick97-git commented on README.md
> +
what about USERNAME and PASSWORD examples?

2021-12-15 10:08 UTC, Nick97-git commented on README.md
> +    * Chose war exploded
```suggestion
2. Configure Tomcat in IDE
```

2021-12-15 10:08 UTC, Nick97-git commented on README.md
> +    * Refresh All
```suggestion
3. Create a schema in MySQL Workbench using file `src/main/resources/init_db.sql`:
```

2021-12-15 13:14 UTC, Nick97-git commented
also, you didn't make changes according to the comment about redundant `/`

2021-12-15 13:14 UTC, Nick97-git requested changes

2021-12-15 13:14 UTC, Nick97-git commented on README.md
> +     private static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
unite them in one

2021-12-15 13:34 UTC, Nick97-git approved these changes

2021-12-15 17:14 UTC, closed without merging